const creators=[
{id:'hg',name:'HGuitare',sub:'Les bases, dans le bon ordre',photo:'avatars/hg.jpg',lang:'fr',levels:[0],tags:['Rock','Théorie'],desc:'Des cours structurés, pas à pas, pour prendre de bonnes habitudes dès les premiers accords.',strength:'Un vrai parcours, du premier accord au premier riff.',score:'4.9',style:'Cours structurés et démonstrations pas à pas',start:'Cours de guitare électrique pour débutant',video:'https://www.hguitare.com/cours-de-guitare-electrique-debutant',youtube:'https://www.youtube.com/user/Hguitare',site:'https://www.hguitare.com/',instagram:'https://www.instagram.com/hguitare/'},
{id:'galago',name:'Galago Music',sub:'Eric Legaud',photo:'avatars/galago.jpg',lang:'fr',levels:[0,1],tags:['Rock','Théorie'],desc:'Vos morceaux préférés décortiqués avec humour, une théorie accessible et beaucoup de musicalité.',strength:'Apprendre un morceau et comprendre ce que l’on joue.',score:'4.9',style:'Tutos de morceaux et accompagnement chaleureux',start:'Bien commencer la guitare — sélection débutant',video:'https://www.galagomusic.com/apprendre-la-guitare/apprendre-a-jouer-de-la-guitare-facilement/',youtube:'https://www.youtube.com/@MrGalagomusic',site:'https://www.galagomusic.com/',instagram:'https://www.instagram.com/galago_music/'},
{id:'neo',name:'NeoGeoFanatic',sub:'La passion du gros son',photo:'avatars/neo.jpg',lang:'fr',levels:[1,2],tags:['Rock','Metal','Shred'],desc:'Du riff au solo : technique, tests de matériel et culture rock avec une énergie communicative.',strength:'Le rock et le metal, avec une vraie culture du son.',score:'4.8',style:'Démonstrations, technique et conseils matériel',start:'Les cours et astuces de NeoGeoFanatic',video:'https://neogeofanatic.fr/pedago-gratuite/',youtube:'https://www.youtube.com/@NeoGeofanatic',site:'https://neogeofanatic.fr/'},
{id:'impro',name:'Guitare Improvisation',sub:'Martin · comprendre avant de soloter',photo:'avatars/impro.jpg',lang:'fr',levels:[1,2],tags:['Blues','Jazz','Théorie'],desc:'Comprenez l’harmonie, explorez les gammes et faites vos premiers pas vers des solos personnels.',strength:'Relier la théorie à la pratique de l’improvisation.',score:'4.9',style:'Théorie appliquée, exemples et exercices progressifs',start:'Débuter en improvisation',video:'https://www.youtube.com/watch?v=ZPmo0cF-Y0o',youtube:'https://www.youtube.com/c/GuitareImprovisationCom',site:'https://www.guitare-improvisation.com/'},
{id:'judge',name:'Judge Fredd',sub:'Guitares, amplis et pédales branchés',photo:'avatars/judge.jpg',lang:'fr',levels:[1],tags:['Rock','Metal'],desc:'Démos, guitares, amplis et effets : des repères pour affiner votre oreille et façonner votre son.',strength:'Comprendre le matériel en l’écoutant vraiment.',score:'4.7',style:'Tests directs, comparatifs et démonstrations sonores',start:'Découvrir les vidéos guitare et matériel',video:'https://www.youtube.com/@JudgeFredd/videos',youtube:'https://www.youtube.com/@JudgeFredd'},
{id:'my',name:'MyGuitare / Julien',sub:'Des morceaux dès les premières semaines',photo:'avatars/my.jpg',lang:'fr',levels:[0],tags:['Rock','Blues'],desc:'Une approche progressive et des morceaux accessibles pour commencer à jouer sans se décourager.',strength:'Des objectifs simples pour garder l’envie de jouer.',score:'4.8',style:'Méthode progressive et exercices concrets',start:'Le guide pour apprendre la guitare',video:'https://www.myguitare.com/guide/',youtube:'https://www.youtube.com/myguitare',site:'https://www.myguitare.com/'},
{id:'romain',name:'Romain Campoy',sub:'Un riff, une nouvelle idée',photo:'avatars/romain.jpg',lang:'fr',levels:[1],tags:['Rock','Blues'],desc:'Des astuces concrètes et des idées de riffs pour enrichir votre jeu et gagner en aisance.',strength:'Des conseils à mettre immédiatement sous les doigts.',score:'4.8',style:'Capsules dynamiques et exercices rapides',start:'Premier cours d’improvisation',video:'https://www.youtube.com/watch?v=LOlKj7PSBuU',youtube:'https://www.youtube.com/RomainCampoy',site:'https://stripmymind.com/'},
{id:'justin',name:'JustinGuitar',sub:'Justin Sandercoe',photo:'avatars/justin.jpg',lang:'en',levels:[0,1],tags:['Rock','Blues','Théorie'],desc:'Un parcours progressif en anglais, des premiers accords aux techniques essentielles.',strength:'Une progression pédagogique particulièrement structurée.',score:'4.9',style:'Parcours complet, exercices et plans de pratique',start:'Beginner Guitar Course — Grade 1',video:'https://www.justinguitar.com/classes/beginner-guitar-course-grade-one',youtube:'https://www.youtube.com/@justinguitar',site:'https://www.justinguitar.com/'},
{id:'bernth',name:'Bernth',sub:'Technique et précision',photo:'avatars/bernth.jpg',lang:'en',levels:[1,2],tags:['Metal','Shred'],desc:'Des exercices ciblés pour travailler la synchronisation, la précision et la vitesse des deux mains.',strength:'Des routines techniques pour dépasser un plateau.',score:'4.8',style:'Exercices courts, métronomiques et très ciblés',start:'Commencer par les exercices techniques',video:'https://www.youtube.com/@Bernthguitar/videos',youtube:'https://www.youtube.com/@Bernthguitar',tiktok:'https://www.tiktok.com/@bernthofficial',site:'https://bernth.at/'},
{id:'paul',name:'Paul Davids',sub:'Son, harmonie et toucher',photo:'avatars/paul.jpg',lang:'en',levels:[1,2],tags:['Blues','Théorie','Jazz'],desc:'Des explorations musicales soignées pour comprendre la guitare et donner du caractère à votre jeu.',strength:'Faire entendre la musique derrière la technique.',score:'4.9',style:'Explications visuelles et théorie musicale appliquée',start:'Les fondamentaux et erreurs à éviter',video:'https://www.youtube.com/@PaulDavids/videos',youtube:'https://www.youtube.com/@PaulDavids',site:'https://pauldavidsguitar.com/'},
{id:'marty',name:'Marty Music',sub:'Marty Schwartz',photo:'avatars/marty.jpg',lang:'en',levels:[0,1],tags:['Rock','Blues'],desc:'Des classiques expliqués simplement, riff par riff, avec une approche chaleureuse et directe.',strength:'Jouer rapidement un morceau que l’on aime.',score:'4.8',style:'Tutos très directs, section par section',start:'Your Very First Electric Guitar Lesson',video:'https://www.youtube.com/watch?v=RY3AvEGKfZ0',youtube:'https://www.youtube.com/@MartyMusic',site:'https://www.martymusic.com/'}
];
const resources=[
{name:'JustinGuitar — Beginner Course',lang:'en',type:'course',badge:'Parcours complet',desc:'Un cursus gratuit et progressif, avec exercices, routines et suivi par niveaux.',url:'https://www.justinguitar.com/classes/beginner-guitar-course-grade-one',source:'JustinGuitar'},
{name:'Galago Music — Tutos gratuits',lang:'fr',type:'library',badge:'370+ tutos',desc:'Morceaux, bases, théorie et accompagnement expliqués en français avec pédagogie.',url:'https://www.galagomusic.com/apprendre-la-guitare/',source:'Galago Music'},
{name:'Guitare Improvisation',lang:'fr',type:'library',badge:'Impro & théorie',desc:'Cours et vidéos pour comprendre les gammes, le blues, le jazz et construire ses solos.',url:'https://www.guitare-improvisation.com/',source:'Guitare Improvisation'},
{name:'HGuitare — Démonstrations',lang:'fr',type:'course',badge:'Cours d’essai',desc:'Une sélection de cours accessibles pour tester la méthode et commencer l’électrique.',url:'https://www.hguitare.com/cours-de-guitare-electrique-debutant',source:'HGuitare'},
{name:'MyGuitare — Guides gratuits',lang:'fr',type:'library',badge:'Guides pratiques',desc:'Des articles et vidéos sur les bases, l’oreille, le rythme et l’improvisation.',url:'https://www.myguitare.com/guide/',source:'MyGuitare'},
{name:'NeoGeoFanatic — Pédago gratuite',lang:'fr',type:'library',badge:'Rock & technique',desc:'Cours gratuits, astuces de jeu et techniques pour le rock et le metal.',url:'https://neogeofanatic.fr/pedago-gratuite/',source:'NeoGeoFanatic'},
{name:'Marty Music — Beginner Electric',lang:'en',type:'course',badge:'Série débutant',desc:'Une première série pour découvrir la guitare électrique et jouer des riffs connus.',url:'https://www.youtube.com/watch?v=RY3AvEGKfZ0',source:'Marty Music'},
{name:'Fender — Articles & accords',lang:'en',type:'library',badge:'Bibliothèque',desc:'Guides gratuits sur les accords, les riffs, la technique et l’entretien.',url:'https://www.fender.com/articles/techniques',source:'Fender'}
];
const levelNames=['Débutant','Intermédiaire','Avancé'],styles=['Rock','Metal','Blues','Jazz','Théorie','Shred'];
const state={lang:'fr',level:'all',platform:'all',style:'all',query:'',tab:'discover',resource:'all'};
let favorites;try{const stored=JSON.parse(localStorage.getItem('accord-favorites')||'[]');favorites=new Set(Array.isArray(stored)?stored:[])}catch{favorites=new Set()}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filtered(){return creators.filter(c=>(state.lang==='all'||c.lang===state.lang)&&(state.level==='all'||c.levels.includes(+state.level))&&(state.platform==='all'||c[state.platform])&&(state.style==='all'||c.tags.includes(state.style))&&norm([c.name,c.sub,c.desc,c.strength,...c.tags].join(' ')).includes(norm(state.query)));}
function card(c){const fav=favorites.has(c.id);return `<article class="card" data-id="${c.id}" tabindex="0" aria-label="Voir la fiche de ${c.name}"><button class="heart ${fav?'saved':''}" data-fav="${c.id}" aria-label="${fav?'Retirer':'Ajouter'} ${c.name} ${fav?'des':'aux'} favoris">${uiIcon("heart")}</button><div class="card-top"><div class="avatar"><img src="${c.photo}" alt="Portrait de ${c.name}" loading="lazy"><span class="verified" title="Sélection Rifty">${uiIcon("check")}</span></div><div><h3>${c.name}<span class="flag">${c.lang==='fr'?'🇫🇷':'🇬🇧'}</span></h3><div class="subname">${c.sub}</div><div class="platforms"><span>${brandIcon("youtube")} YouTube</span>${c.tiktok?`<span>${brandIcon('tiktok')} TikTok</span>`:''}</div></div></div><div class="levels">${c.levels.map(l=>`<span class="level l${l}"><i class="dot ${['green','orange','red'][l]}"></i>${levelNames[l]}</span>`).join('')}<span class="score">★ ${c.score}<small>/5 · score Rifty</small></span></div><div class="tags">${c.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p class="desc">${c.desc}</p><div class="special"><strong>Pourquoi on le garde</strong><p>${c.strength}</p></div><div class="card-bottom"><span>Voir le détail</span><a class="open" href="${c.youtube}" target="_blank" rel="noopener" data-open>Ouvrir ${uiIcon("arrow-up-right")}</a></div></article>`}
function renderCreators(){const list=filtered();$('#grid').innerHTML=list.map(card).join('');$('#count').textContent=`${list.length} créateur${list.length>1?'s':''}`;$('#empty').hidden=!!list.length;$('#clear').hidden=!state.query;$$('[data-filter]').forEach(g=>g.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',state[g.dataset.filter]===b.dataset.value)));$$('#style-chips button').forEach(b=>b.classList.toggle('active',b.dataset.style===state.style));bindCards($('#grid'));}
function bindCards(){}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('accord-favorites',JSON.stringify([...favorites]));localStorage.setItem('rifty-local-updated',String(Date.now()));updateFavorites();renderCreators();showToast(favorites.has(id)?'Ajouté à votre profil':'Retiré de votre profil');}
function updateFavorites(){const list=creators.filter(c=>favorites.has(c.id));$('#fav-count').textContent=list.length;$('#favorite-grid').innerHTML=list.map(card).join('');$('#favorites-empty').hidden=!!list.length;bindCards($('#favorite-grid'));document.dispatchEvent(new Event('accord:favorites'));}
function openDetail(id){const c=creators.find(x=>x.id===id),note=localStorage.getItem(`accord-note-${id}`)||'';$('#detail-content').innerHTML=`<button class="close detail-close" aria-label="Fermer">${uiIcon("x")}</button><div class="detail-hero"><div class="detail-avatar"><img src="${c.photo}" alt="Portrait de ${c.name}"></div><div><span class="kicker">FICHE CRÉATEUR</span><h2>${c.name} ${c.lang==='fr'?'🇫🇷':'🇬🇧'}</h2><p>${c.sub}</p><button class="heart detail-heart ${favorites.has(id)?'saved':''}" data-fav="${id}">${uiIcon("heart")} ${favorites.has(id)?"Dans mes favoris":"Ajouter aux favoris"}</button></div></div><div class="detail-grid"><section><span class="detail-label">POUR COMMENCER</span><a class="video-card" href="${c.video}" target="_blank" rel="noopener"><span class="play">${uiIcon("play")}</span><div><strong>${c.start}</strong><small>Ouvrir la recommandation ↗</small></div></a></section><section><span class="detail-label">STYLE D’ENSEIGNEMENT</span><p>${c.style}</p></section><section><span class="detail-label">RÉSEAUX & SITE</span><div class="social-links"><a href="${c.youtube}" target="_blank" rel="noopener">${brandIcon("youtube")} YouTube ${uiIcon("arrow-up-right")}</a>${c.tiktok?`<a href="${c.tiktok}" target="_blank" rel="noopener">${brandIcon("tiktok")} TikTok ${uiIcon("arrow-up-right")}</a>`:''}${c.instagram?`<a href="${c.instagram}" target="_blank" rel="noopener">Instagram ↗</a>`:''}${c.site?`<a href="${c.site}" target="_blank" rel="noopener">Site web ↗</a>`:''}</div></section><section><span class="detail-label">VOTRE AVIS PRIVÉ</span><p class="review-help">Votre note reste sur cet appareil.</p><textarea id="personal-review" placeholder="Ce qui vous aide chez ce créateur…">${note.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}</textarea><button class="secondary" id="save-review">Enregistrer mon avis</button></section></div>`;$('#detail').showModal();$('.detail-close').onclick=()=>$('#detail').close();$('#save-review').onclick=()=>{localStorage.setItem(`accord-note-${id}`,$('#personal-review').value);showToast('Votre avis est enregistré')};}
function switchTab(tab){state.tab=tab;document.body.dataset.activeTab=tab;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===tab));if(tab==='profile')updateFavorites();document.dispatchEvent(new Event('accord:tab'));if(tab!=='tools')stopAudio();scrollTo({top:0,behavior:'smooth'});}
function renderResources(){const list=resources.filter(r=>state.resource==='all'||r.lang===state.resource||r.type===state.resource);$('#resource-grid').innerHTML=list.map(r=>`<article class="resource-card"><div class="resource-top"><span class="free-badge">GRATUIT</span><span>${r.lang==='fr'?'🇫🇷 Français':'🇬🇧 Anglais'}</span></div><span class="resource-type">${r.badge}</span><h3>${r.name}</h3><p>${r.desc}</p><div><span>Par ${r.source}</span><a href="${r.url}" target="_blank" rel="noopener">Explorer ↗</a></div></article>`).join('')}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2200)}
$('#style-chips').innerHTML=`<button class="active" data-style="all">Tous les styles</button>${styles.map(s=>`<button data-style="${s}">${s}</button>`).join('')}`;
$$('[data-filter]').forEach(g=>g.onclick=e=>{const b=e.target.closest('button');if(!b)return;state[g.dataset.filter]=b.dataset.value;renderCreators()});$('#style-chips').onclick=e=>{const b=e.target.closest('button');if(b){state.style=b.dataset.style;renderCreators()}};$('#search').oninput=e=>{state.query=e.target.value;renderCreators()};$('#clear').onclick=()=>{$('#search').value='';state.query='';renderCreators()};$('#reset').onclick=()=>{Object.assign(state,{lang:'all',level:'all',platform:'all',style:'all',query:''});$('#search').value='';renderCreators()};
$('#surprise').onclick=()=>{const list=filtered();if(!list.length)return showToast('Aucun créateur avec ces filtres');openDetail(list[Math.floor(Math.random()*list.length)].id)};
$$('[data-tab], [data-tab-link]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();switchTab(button.dataset.tab||button.dataset.tabLink)}));
const root=document.documentElement;function setTheme(theme){root.dataset.theme=theme;localStorage.setItem('accord-theme',theme);$('#theme-toggle').setAttribute('aria-label',theme==='dark'?'Activer le mode clair':'Activer le mode nuit');document.querySelector('meta[name=theme-color]').content=theme==='dark'?'#0a0b0e':'#f5f7fa'}setTheme(root.dataset.theme||'light');$('#theme-toggle').onclick=()=>setTheme(root.dataset.theme==='dark'?'light':'dark');
$$('[data-resource-filter]').forEach(b=>b.onclick=()=>{state.resource=b.dataset.resourceFilter;$$('[data-resource-filter]').forEach(x=>x.classList.toggle('active',x===b));renderResources()});
let audioCtx=null,metroTimer=null,osc=null,beat=0;function ctx(){return audioCtx||(audioCtx=new (window.AudioContext||window.webkitAudioContext)())}function tick(){const ac=ctx(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=beat++%4===0?1000:750;g.gain.setValueAtTime(.07,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.05);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.06);$('#beat-orb').classList.remove('pulse');void $('#beat-orb').offsetWidth;$('#beat-orb').classList.add('pulse')}function startMetro(){stopMetro();tick();metroTimer=setInterval(tick,60000/Number($('#bpm').value));$('#metro-toggle').textContent='Arrêter';$('#metro-toggle').classList.add('running')}function stopMetro(){clearInterval(metroTimer);metroTimer=null;$('#metro-toggle').textContent='Démarrer';$('#metro-toggle').classList.remove('running')}$('#bpm').oninput=e=>{$('#bpm-value').textContent=e.target.value;if(metroTimer)startMetro()};$('#metro-toggle').onclick=()=>metroTimer?stopMetro():startMetro();
const notes=[['E',82.41],['A',110],['D',146.83],['G',196],['B',246.94],['E',329.63]];$('#tuner-notes').innerHTML=notes.map((n,i)=>`<button data-note="${i}"><strong>${n[0]}</strong><small>${i+1}</small></button>`).join('');function playTone(i){stopTone();const [name,freq]=notes[i],ac=ctx();osc=ac.createOscillator();const gain=ac.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.value=.07;osc.connect(gain).connect(ac.destination);osc.start();$('#note-display').textContent=name;$('#freq-display').textContent=`${freq} Hz · corde ${i+1}`;$('#wave').classList.add('playing');$('#stop-tone').disabled=false;$$('[data-note]').forEach((b,j)=>b.classList.toggle('active',j===i))}function stopTone(){if(osc){osc.stop();osc=null}$('#wave').classList.remove('playing');$('#stop-tone').disabled=true;$$('[data-note]').forEach(b=>b.classList.remove('active'))}function stopAudio(){stopMetro();stopTone()}$$('[data-note]').forEach(b=>b.onclick=()=>playTone(+b.dataset.note));$('#stop-tone').onclick=stopTone;
const sheet=$('#sheet');$$('[data-suggest]').forEach(b=>b.onclick=()=>sheet.showModal());$('#sheet .close').onclick=()=>sheet.close();$('#suggest-form').onsubmit=e=>{e.preventDefault();const f=e.target,u=f.elements.url;let parsed;try{parsed=new URL(u.value)}catch{u.setCustomValidity('Ajoutez une URL valide');u.reportValidity();return}if(!/(youtube\.com|youtu\.be|tiktok\.com)$/.test(parsed.hostname)){u.setCustomValidity('Ajoutez un lien YouTube ou TikTok');u.reportValidity();return}const saved=JSON.parse(localStorage.getItem('accord-suggestions')||'[]');saved.push({name:f.elements.name.value,url:parsed.href,note:f.elements.note.value,date:new Date().toISOString()});localStorage.setItem('accord-suggestions',JSON.stringify(saved));f.reset();$('#form-status').textContent='✓ Suggestion enregistrée sur cet appareil.'};$('[name=url]').oninput=e=>e.target.setCustomValidity('');
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab], [data-tab-link]');if(tab){e.preventDefault();switchTab(tab.dataset.tab||tab.dataset.tabLink);return}const fav=e.target.closest('[data-fav]');if(fav){e.preventDefault();e.stopPropagation();const inDetail=fav.closest('#detail'),id=fav.dataset.fav;toggleFavorite(id);if(inDetail){$('#detail').close();openDetail(id)}return}const card=e.target.closest('.card');if(card&&!e.target.closest('[data-open]'))openDetail(card.dataset.id)});
document.addEventListener('keydown',e=>{const card=e.target.closest('.card');if(card&&e.key==='Enter'&&!e.target.closest('button,a'))openDetail(card.dataset.id)});
document.addEventListener('rifty:cloud-loaded',()=>{try{const stored=JSON.parse(localStorage.getItem('accord-favorites')||'[]');favorites=new Set(Array.isArray(stored)?stored:[])}catch{favorites=new Set()}updateFavorites();renderCreators()});
[$('#sheet'),$('#detail')].forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});document.body.dataset.activeTab='discover';renderCreators();updateFavorites();renderResources();
