(()=>{
  const byId=id=>document.getElementById(id),auth=window.RiftyAuth;
  const isoWeek=(()=>{const now=new Date(),date=new Date(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())),day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()+4-day);const yearStart=new Date(Date.UTC(date.getUTCFullYear(),0,1));return {year:date.getUTCFullYear(),week:Math.ceil((((date-yearStart)/86400000)+1)/7)}})();
  const challenge={slug:`pentatonique-mi-${isoWeek.year}-s${isoWeek.week}`,goal:2500,xp:50};
  let selectedFile=null,previewUrl=null,loading=false;
  byId('challenge-week').textContent=`SEMAINE ${isoWeek.week} · DÉFI OUVERT`;
  byId('community-progress').max=challenge.goal;

  function setStatus(text,type=''){const el=byId('challenge-status');el.textContent=text;el.dataset.type=type}
  function displayName(){try{const profile=JSON.parse(localStorage.getItem('accord-profile')||'{}');if(profile.nickname?.trim())return profile.nickname.trim().slice(0,40)}catch{}const user=auth?.session?.user;return (user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'Guitariste').slice(0,40)}
  function setParticipationState(){const connected=!!auth?.session;byId('challenge-form').hidden=!connected;byId('challenge-auth-needed').hidden=connected;if(!auth?.configured){byId('challenge-form').hidden=true;byId('challenge-auth-needed').hidden=false;byId('challenge-auth-needed').querySelector('h3').textContent='La communauté est prête à être activée.';byId('challenge-auth-needed').querySelector('p').textContent='Renseignez Supabase pour publier les vidéos et cumuler les XP du groupe.'}}
  function timeAgo(value){const seconds=Math.max(0,Math.floor((Date.now()-new Date(value))/1000));if(seconds<60)return 'À l’instant';if(seconds<3600)return `Il y a ${Math.floor(seconds/60)} min`;if(seconds<86400)return `Il y a ${Math.floor(seconds/3600)} h`;return new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}
  function renderFeed(posts){
    const feed=byId('community-feed');feed.replaceChildren();byId('community-empty').hidden=posts.length>0;
    for(const post of posts){const card=document.createElement('article');card.className='community-post';const video=document.createElement('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.src=auth.client.storage.from('rifty-challenges').getPublicUrl(post.video_path).data.publicUrl;const body=document.createElement('div');body.className='community-post-body';const head=document.createElement('div');const name=document.createElement('strong');name.textContent=post.display_name||'Guitariste';const xp=document.createElement('span');xp.textContent=`+${post.xp_awarded||challenge.xp} XP groupe`;head.append(name,xp);body.append(head);if(post.caption){const caption=document.createElement('p');caption.textContent=post.caption;body.append(caption)}const date=document.createElement('small');date.textContent=timeAgo(post.created_at);body.append(date);card.append(video,body);feed.append(card)}
    const xp=posts.reduce((sum,post)=>sum+(Number(post.xp_awarded)||0),0),people=new Set(posts.map(post=>post.user_id)).size;byId('community-xp').textContent=xp.toLocaleString('fr-FR');byId('community-participants').textContent=`${people} guitariste${people>1?'s':''}`;byId('community-progress').value=Math.min(xp,challenge.goal);byId('community-goal-copy').textContent=xp>=challenge.goal?'Objectif collectif atteint !':`${Math.max(0,challenge.goal-xp).toLocaleString('fr-FR')} XP avant l’objectif`;
  }
  async function loadFeed(){
    if(!auth?.configured||!auth.client){renderFeed([]);return}
    if(loading)return;loading=true;byId('community-refresh').classList.add('loading');
    const {data,error}=await auth.client.from('rifty_challenge_posts').select('id,user_id,display_name,caption,video_path,xp_awarded,created_at').eq('challenge_slug',challenge.slug).order('created_at',{ascending:false}).limit(18);
    loading=false;byId('community-refresh').classList.remove('loading');
    if(error){byId('community-empty').hidden=false;byId('community-empty').querySelector('strong').textContent='Le défi attend sa configuration.';byId('community-empty').querySelector('p').textContent=['42P01','PGRST205'].includes(error.code)?'Exécutez la nouvelle version de supabase-schema.sql.':error.message;return}renderFeed(data||[])
  }
  function videoDuration(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';video.onloadedmetadata=()=>{const duration=video.duration;URL.revokeObjectURL(url);resolve(duration)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Vidéo illisible'))};video.src=url})}
  byId('challenge-video').onchange=async e=>{const file=e.target.files[0];selectedFile=null;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null}byId('challenge-preview').hidden=true;if(!file)return;if(!['video/mp4','video/webm','video/quicktime'].includes(file.type))return setStatus('Choisissez une vidéo MP4, WebM ou MOV.','error');if(file.size>25*1024*1024)return setStatus('La vidéo doit peser moins de 25 Mo.','error');try{const duration=await videoDuration(file);if(!Number.isFinite(duration)||duration>30.5)return setStatus('La vidéo doit durer 30 secondes maximum.','error');selectedFile=file;previewUrl=URL.createObjectURL(file);byId('challenge-preview').src=previewUrl;byId('challenge-preview').hidden=false;byId('challenge-file-label').textContent=file.name;setStatus(`${Math.ceil(duration)} secondes · prête à publier.`,'success')}catch(error){setStatus(error.message,'error')}};
  byId('challenge-form').onsubmit=async e=>{e.preventDefault();if(!auth?.session){auth?.open();return}if(!auth.nickname)return setStatus('Choisissez d’abord votre pseudo dans les réglages de votre profil.','error');if(!selectedFile)return setStatus('Choisissez d’abord une courte vidéo.','error');const button=byId('challenge-submit');button.disabled=true;button.textContent='Publication…';setStatus('Envoi sécurisé de votre contribution…');const extension=(selectedFile.name.split('.').pop()||'mp4').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,5)||'mp4',path=`${auth.session.user.id}/${challenge.slug}-${crypto.randomUUID()}.${extension}`;const upload=await auth.client.storage.from('rifty-challenges').upload(path,selectedFile,{contentType:selectedFile.type,upsert:false});if(upload.error){button.disabled=false;button.textContent='Publier ma contribution';return setStatus(upload.error.message,'error')}const insert=await auth.client.from('rifty_challenge_posts').insert({user_id:auth.session.user.id,challenge_slug:challenge.slug,display_name:displayName(),caption:byId('challenge-caption').value.trim()||null,video_path:path});if(insert.error){await auth.client.storage.from('rifty-challenges').remove([path]);button.disabled=false;button.textContent='Publier ma contribution';return setStatus(insert.error.code==='23505'?'Vous avez déjà participé à ce défi.':insert.error.message,'error')}setStatus(`Contribution publiée · +${challenge.xp} XP pour le groupe !`,'success');e.target.reset();selectedFile=null;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null;byId('challenge-preview').hidden=true;byId('challenge-file-label').textContent='Choisir une courte vidéo';button.disabled=false;button.textContent='Publier ma contribution';loadFeed()};
  byId('community-refresh').onclick=loadFeed;
  document.addEventListener('rifty:auth-change',()=>{setParticipationState();loadFeed()});
  document.addEventListener('accord:tab',()=>{if(document.body.dataset.activeTab==='community')loadFeed()});
  setParticipationState();loadFeed();
})();
