/* Daily XP is derived from a dated ledger: rechecking never duplicates rewards. */
(function(root){
  const missions=[{id:'discover',title:'Découvrir un créateur',detail:'Ouvrez une fiche que vous ne connaissez pas encore.',xp:20,icon:'search'},{id:'practice',title:'Pratiquer pendant 15 minutes',detail:'Lancez le chrono et jouez ce qui vous bloque en ce moment.',xp:50,icon:'music2'},{id:'learn',title:'Suivre un cours ou un tutoriel',detail:'Prenez une seule idée du cours et mettez-la sous les doigts.',xp:30,icon:'book-open'}];
  function dayKey(date=new Date()){return [date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-')}
  function clean(raw){const ledger={};if(raw&&typeof raw==='object'&&!Array.isArray(raw))for(const [day,ids]of Object.entries(raw)){if(/^\d{4}-\d{2}-\d{2}$/.test(day)&&Array.isArray(ids))ledger[day]=[...new Set(ids.filter(id=>missions.some(m=>m.id===id)))];}return ledger;}
  function toggle(ledger,day,id,checked){if(!missions.some(m=>m.id===id))throw new Error('Mission inconnue');const next=clean(ledger),set=new Set(next[day]||[]);checked?set.add(id):set.delete(id);next[day]=[...set];return next;}
  function streak(ledger,now=new Date()){const days=clean(ledger),practiced=day=>Array.isArray(days[day])&&days[day].includes('practice'),cursor=new Date(now.getFullYear(),now.getMonth(),now.getDate());let current=0;if(!practiced(dayKey(cursor)))cursor.setDate(cursor.getDate()-1);while(practiced(dayKey(cursor))){current++;cursor.setDate(cursor.getDate()-1)}const keys=Object.keys(days).filter(practiced).sort();let longest=0,run=0,previous=null;for(const key of keys){const date=new Date(`${key}T12:00:00`);if(previous){const gap=Math.round((date-previous)/86400000);run=gap===1?run+1:1}else run=1;longest=Math.max(longest,run);previous=date}return {current,longest,practicedToday:practiced(dayKey(now))}}
  function stats(ledger,day){const days=clean(ledger),points=ids=>missions.reduce((sum,m)=>sum+(ids.includes(m.id)?m.xp:0),0),total=Object.values(days).reduce((sum,ids)=>sum+points(ids),0),today=days[day]||[],series=streak(days,new Date(`${day}T12:00:00`));return {total,today:points(today),completed:today.length,rank:Math.floor(total/200)+1,rankXP:total%200,practiceDays:Object.values(days).filter(ids=>ids.includes('practice')).length,streak:series.current,longestStreak:series.longest,practicedToday:series.practicedToday};}
  const api={missions,dayKey,clean,toggle,streak,stats};if(typeof module!=='undefined')module.exports=api;else root.RiftyProgress=api;
})(typeof window!=='undefined'?window:globalThis);
